### PR TITLE
Added method for update

### PR DESCRIPTION
**Pull request by matbesancon**
First take on https://github.com/JuliaSmoothOptimizers/BasicLU.jl/issues/23, at least to have a function there before updating the base library itself

### CODE REVIEW

**Comment by matbesancon** [comment]
Should be merged after #25 only

**Comment by amontoison** [comment]
We have a conflict with `src/BasicLU.jl`.

**Comment by amontoison** [comment]
Do you want a new release Mathieu?

**Comment by matbesancon** [comment]
Would be great yes, nothing urgent on my side though for now

**Comment by matbesancon** [comment]
@lschork2 would you be interested in having this in basiclu itself?

**Pull request merged**
